<table border="0" cellspacing="0" cellpadding="5" width="100%" class="table">
  <tr>
    <th width="15%" align="center" >
      <p>Cost center</p>
    </th>
    <th width="30%" align="center" >
      <p>Work order</p>
    </th>
    <th width="10%" align="center" >
      <p>Percentage</p>
    </th>
    <th width="15%" align="center" >
      <p>Value</p>
    </th>
    <th width="35%" align="center" >
      <p>Remarks</p>
    </th>
  </tr>
  $datachargecodes$
</table>
