<tr>
  <td width="20%" align="left" class="zebra">$startpoint$</td>
  <td width="20%" align="left" class="zebra">$endpoint$</td>
  <td width="15%" align="left" class="zebra">$classoftravel$</td>
  <td width="15%" align="left" class="zebra">$travel_date_label$</td>
  <td width="15%" align="left" class="zebra">$travel_time_label$</td>
  <!--<td width="15%" align="left" class="zebra">$travel_type$</td>-->
  <td width="15%" align="left" class="zebra">$remarks$</td>
</tr>

