<table border="0" cellspacing="0" cellpadding="5" width="100%" class="table">
  <tr>
    <th width="20%" align="center" style="border-bottom: #C2D69A solid 1px;" class="header2">
      <p>Departure</p>
    </th>
    <th width="20%" align="center" style="border-bottom: #C2D69A solid 1px;" class="header2">
      <p>Arrival</p>
    </th>
    <th width="15%" align="center" style="border-bottom: #C2D69A solid 1px;" class="header2">
      <p>Class</p>
    </th>
    <th width="15%" align="center" style="border-bottom: #C2D69A solid 1px;" class="header2">
      <p>Date</p>
    </th>
    <th width="15%" align="center" style="border-bottom: #C2D69A solid 1px;" class="header2">
      <p>Time</p>
    </th>
    <!--<th width="15%" align="center" style="border-bottom: #C2D69A solid 1px;" class="header2">
      <p>Travel type</p>
    </th>-->
    <th width="15%" align="center" style="border-bottom: #C2D69A solid 1px;" class="header2">
      <p>Remarks</p>
    </th>
  </tr>
  $itinerary$
</table>
