<tr>
  <td width="20%" align="left" class="basefont">$startpoint$</td>
  <td width="20%" align="left" class="basefont">$endpoint$</td>
  <td width="15%" align="left" class="basefont">$classoftravel$</td>
  <td width="15%" align="left" class="basefont">$travel_date_label$</td>
  <td width="15%" align="left" class="basefont">$travel_time_label$</td>
  <!--<td width="15%" align="left" class="basefont">$travel_type$</td>-->
  <td width="15%" align="left" class="basefont">$remarks$</td>
</tr>